const products = [
  {
    id: 1, sku: "ELEC-001",
    name: { fr: "Casque Audio Premium", en: "Premium Headphones", de: "Premium Kopfhörer", es: "Auriculares Premium" },
    category: "electronics",
    price: 249.99, oldPrice: 319.99,
    rating: 4.8, reviews: 234,
    stock: 15, featured: true, isNew: false, onSale: true,
    colors: ["#1a1a2e", "#c0392b", "#2c3e50"],
    sizes: [],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80",
      "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=600&q=80"
    ],
    description: {
      fr: "Casque audio haute fidélité avec réduction de bruit active. Son cristallin et basses profondes pour une expérience d'écoute immersive.",
      en: "High-fidelity headphones with active noise cancellation. Crystal clear sound and deep bass for an immersive listening experience.",
      de: "High-Fidelity-Kopfhörer mit aktiver Geräuschunterdrückung. Kristallklarer Sound für ein immersives Hörerlebnis.",
      es: "Auriculares de alta fidelidad con cancelación activa de ruido. Sonido cristalino y bajos profundos para una experiencia inmersiva."
    },
    specs: { fr: "Driver 40mm · Bluetooth 5.0 · 30h autonomie · USB-C", en: "40mm driver · Bluetooth 5.0 · 30h battery · USB-C", de: "40mm Treiber · Bluetooth 5.0 · 30h Akku · USB-C", es: "Driver 40mm · Bluetooth 5.0 · 30h batería · USB-C" }
  },
  {
    id: 2, sku: "FASH-001",
    name: { fr: "Veste en Cuir Vintage", en: "Vintage Leather Jacket", de: "Vintage-Lederjacke", es: "Chaqueta de Cuero Vintage" },
    category: "fashion",
    price: 189.99, oldPrice: null,
    rating: 4.6, reviews: 89,
    stock: 8, featured: true, isNew: true, onSale: false,
    colors: ["#3d2b1f", "#1a1a1a", "#8B4513"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80","https://images.unsplash.com/photo-1520975916090-3105956dac38?w=600&q=80"],
    description: { fr: "Veste en cuir véritable au style rétro intemporel. Coupe ajustée et finitions soignées.", en: "Genuine leather jacket with timeless retro style. Tailored fit and careful finishing.", de: "Echte Lederjacke mit zeitlosem Retro-Stil.", es: "Chaqueta de cuero genuino con estilo retro atemporal." },
    specs: { fr: "Cuir véritable · Doublure polyester · Machine 30°C", en: "Genuine leather · Polyester lining · Machine 30°C", de: "Echtes Leder · Polyesterfutter", es: "Cuero genuino · Forro poliéster" }
  },
  {
    id: 3, sku: "HOME-001",
    name: { fr: "Lampe Design Scandinave", en: "Scandinavian Design Lamp", de: "Skandinavische Designlampe", es: "Lámpara Diseño Escandinavo" },
    category: "home",
    price: 89.99, oldPrice: 120.00,
    rating: 4.9, reviews: 156,
    stock: 22, featured: true, isNew: false, onSale: true,
    colors: ["#f5f0e8", "#2c2c2c", "#8fbc8f"],
    sizes: [],
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80","https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600&q=80"],
    description: { fr: "Lampe à poser au design épuré scandinave. Lumière chaleureuse et douce pour une ambiance cosy.", en: "Table lamp with clean Scandinavian design. Warm light for a cosy atmosphere.", de: "Tischlampe mit klarem skandinavischem Design.", es: "Lámpara de mesa con diseño escandinavo limpio." },
    specs: { fr: "E27 · 60W max · Hauteur 45cm · Bois + métal", en: "E27 · 60W max · Height 45cm · Wood + metal", de: "E27 · 60W max · Höhe 45cm", es: "E27 · 60W máx · Altura 45cm" }
  },
  {
    id: 4, sku: "ELEC-002",
    name: { fr: "Montre Connectée Sport", en: "Sport Smartwatch", de: "Sport-Smartwatch", es: "Smartwatch Deportivo" },
    category: "electronics",
    price: 199.99, oldPrice: null,
    rating: 4.7, reviews: 312,
    stock: 30, featured: false, isNew: true, onSale: false,
    colors: ["#1a1a2e", "#c0392b", "#2ecc71"],
    sizes: [],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80"],
    description: { fr: "Montre connectée avec GPS intégré, suivi santé 24/7 et autonomie jusqu'à 7 jours.", en: "Smartwatch with built-in GPS, 24/7 health tracking and up to 7 days battery.", de: "Smartwatch mit integriertem GPS und 7-Tage-Akku.", es: "Smartwatch con GPS integrado y hasta 7 días de batería." },
    specs: { fr: "GPS · Cardiofréquencemètre · SpO2 · IP68 · 7 jours", en: "GPS · Heart rate · SpO2 · IP68 · 7 days", de: "GPS · Herzfrequenz · SpO2 · IP68", es: "GPS · Frecuencia cardíaca · SpO2 · IP68" }
  },
  {
    id: 5, sku: "BEAU-001",
    name: { fr: "Coffret Parfum Luxe", en: "Luxury Perfume Set", de: "Luxus-Parfüm-Set", es: "Set de Perfume de Lujo" },
    category: "beauty",
    price: 129.99, oldPrice: 159.99,
    rating: 4.5, reviews: 78,
    stock: 12, featured: false, isNew: false, onSale: true,
    colors: [],
    sizes: ["30ml", "50ml", "100ml"],
    image: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80"],
    description: { fr: "Coffret luxueux avec 3 parfums aux notes florales et boisées. Idéal comme cadeau.", en: "Luxurious set with 3 fragrances with floral and woody notes. Perfect as a gift.", de: "Luxuriöses Set mit 3 Düften. Perfekt als Geschenk.", es: "Set lujoso con 3 fragancias florales y amaderadas. Ideal como regalo." },
    specs: { fr: "3 x 30ml · Flacon verre · Coffret cadeau", en: "3 x 30ml · Glass bottle · Gift box", de: "3 x 30ml · Glasflakon · Geschenkbox", es: "3 x 30ml · Frasco de vidrio · Caja regalo" }
  },
  {
    id: 6, sku: "SPRT-001",
    name: { fr: "Sac à Dos Sport Pro", en: "Pro Sport Backpack", de: "Pro Sport Rucksack", es: "Mochila Deportiva Pro" },
    category: "sports",
    price: 79.99, oldPrice: null,
    rating: 4.4, reviews: 201,
    stock: 45, featured: false, isNew: true, onSale: false,
    colors: ["#1a1a2e", "#c0392b", "#2c3e50", "#27ae60"],
    sizes: [],
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80"],
    description: { fr: "Sac à dos sportif ultra-résistant avec compartiment laptop 15\". Idéal pour le gym et les aventures.", en: "Ultra-resistant sport backpack with 15\" laptop compartment. Perfect for gym and adventures.", de: "Ultraresistenter Sport-Rucksack mit 15\" Laptop-Fach.", es: "Mochila deportiva ultraresistente con compartimento para portátil de 15\"." },
    specs: { fr: "30L · Laptop 15\" · Imperméable · 650g", en: "30L · Laptop 15\" · Waterproof · 650g", de: "30L · Laptop 15\" · Wasserdicht · 650g", es: "30L · Portátil 15\" · Impermeable · 650g" }
  },
  {
    id: 7, sku: "ELEC-003",
    name: { fr: "Enceinte Bluetooth Portable", en: "Portable Bluetooth Speaker", de: "Tragbarer Bluetooth-Lautsprecher", es: "Altavoz Bluetooth Portátil" },
    category: "electronics",
    price: 69.99, oldPrice: 89.99,
    rating: 4.6, reviews: 445,
    stock: 28, featured: false, isNew: false, onSale: true,
    colors: ["#1a1a2e", "#c0392b", "#3498db", "#2ecc71"],
    sizes: [],
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80"],
    description: { fr: "Son puissant 360° dans un format compact. Résistante à l'eau IPX7 et 20h d'autonomie.", en: "Powerful 360° sound in a compact format. IPX7 waterproof and 20h battery life.", de: "Leistungsstarker 360°-Sound. IPX7 wasserdicht und 20h Akkulaufzeit.", es: "Sonido 360° potente en formato compacto. Resistente al agua IPX7 y 20h de batería." },
    specs: { fr: "20W · IPX7 · 20h · Bluetooth 5.1 · USB-C", en: "20W · IPX7 · 20h · Bluetooth 5.1 · USB-C", de: "20W · IPX7 · 20h · Bluetooth 5.1", es: "20W · IPX7 · 20h · Bluetooth 5.1" }
  },
  {
    id: 8, sku: "FASH-002",
    name: { fr: "Sneakers Urbaines Édition Limitée", en: "Limited Edition Urban Sneakers", de: "Limited Edition Urban Sneakers", es: "Sneakers Urbanas Edición Limitada" },
    category: "fashion",
    price: 159.99, oldPrice: null,
    rating: 4.8, reviews: 67,
    stock: 5, featured: true, isNew: true, onSale: false,
    colors: ["#f5f0e8", "#1a1a2e", "#c0392b"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80","https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80"],
    description: { fr: "Sneakers haut de gamme en édition limitée. Semelle ultra-confort et design exclusif.", en: "High-end limited edition sneakers. Ultra-comfort sole and exclusive design.", de: "High-End Limited Edition Sneakers mit Ultrakomfort-Sohle.", es: "Sneakers de gama alta edición limitada. Suela ultraconfort y diseño exclusivo." },
    specs: { fr: "Cuir synthétique · Semelle EVA · Lacets plats", en: "Synthetic leather · EVA sole · Flat laces", de: "Kunstleder · EVA-Sohle · Flache Schnürsenkel", es: "Cuero sintético · Suela EVA · Cordones planos" }
  },
  {
    id: 9, sku: "HOME-002",
    name: { fr: "Diffuseur d'Arômes Zen", en: "Zen Aroma Diffuser", de: "Zen-Aromadiffuser", es: "Difusor de Aromas Zen" },
    category: "home",
    price: 49.99, oldPrice: 65.00,
    rating: 4.7, reviews: 189,
    stock: 34, featured: false, isNew: false, onSale: true,
    colors: ["#f5f0e8", "#2c2c2c"],
    sizes: [],
    image: "https://images.unsplash.com/photo-1544816565-aa8c1166648f?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1544816565-aa8c1166648f?w=600&q=80"],
    description: { fr: "Diffuseur ultrasonique avec 7 couleurs LED. Crée une atmosphère relaxante dans votre intérieur.", en: "Ultrasonic diffuser with 7 LED colors. Creates a relaxing atmosphere in your home.", de: "Ultraschall-Diffuser mit 7 LED-Farben.", es: "Difusor ultrasónico con 7 colores LED. Crea un ambiente relajante en tu hogar." },
    specs: { fr: "500ml · 7 couleurs LED · Arrêt auto · Silencieux", en: "500ml · 7 LED colors · Auto shutoff · Silent", de: "500ml · 7 LED-Farben · Automatische Abschaltung", es: "500ml · 7 colores LED · Apagado automático" }
  },
  {
    id: 10, sku: "BOOK-001",
    name: { fr: "Collection Design & Architecture", en: "Design & Architecture Collection", de: "Design & Architektur Kollektion", es: "Colección Diseño y Arquitectura" },
    category: "books",
    price: 45.00, oldPrice: null,
    rating: 4.9, reviews: 43,
    stock: 18, featured: false, isNew: true, onSale: false,
    colors: [],
    sizes: [],
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80"],
    description: { fr: "Coffret de 3 livres d'art sur le design contemporain et l'architecture moderne. Format grand luxe.", en: "Set of 3 art books on contemporary design and modern architecture. Luxury format.", de: "Set aus 3 Kunstbüchern über zeitgenössisches Design und moderne Architektur.", es: "Set de 3 libros de arte sobre diseño contemporáneo y arquitectura moderna." },
    specs: { fr: "3 volumes · Couverture rigide · 350 pages · 25x30cm", en: "3 volumes · Hardcover · 350 pages · 25x30cm", de: "3 Bände · Hardcover · 350 Seiten", es: "3 volúmenes · Tapa dura · 350 páginas" }
  },
  {
    id: 11, sku: "BEAU-002",
    name: { fr: "Skincare Set Premium", en: "Premium Skincare Set", de: "Premium Hautpflege-Set", es: "Set de Cuidado de Piel Premium" },
    category: "beauty",
    price: 94.99, oldPrice: null,
    rating: 4.6, reviews: 112,
    stock: 20, featured: false, isNew: true, onSale: false,
    colors: [],
    sizes: [],
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80"],
    description: { fr: "Routine complète avec sérum, crème de jour et contour des yeux. Formule anti-âge avancée.", en: "Complete routine with serum, day cream and eye contour. Advanced anti-aging formula.", de: "Vollständige Routine mit Serum, Tagescreme und Augenkontur.", es: "Rutina completa con sérum, crema de día y contorno de ojos." },
    specs: { fr: "Sérum 30ml · Crème 50ml · Yeux 15ml · Vegan", en: "Serum 30ml · Cream 50ml · Eye 15ml · Vegan", de: "Serum 30ml · Creme 50ml · Augen 15ml · Vegan", es: "Sérum 30ml · Crema 50ml · Ojos 15ml · Vegano" }
  },
  {
    id: 12, sku: "SPRT-002",
    name: { fr: "Tapis de Yoga Premium", en: "Premium Yoga Mat", de: "Premium Yogamatte", es: "Esterilla de Yoga Premium" },
    category: "sports",
    price: 59.99, oldPrice: 79.99,
    rating: 4.5, reviews: 267,
    stock: 40, featured: false, isNew: false, onSale: true,
    colors: ["#2ecc71", "#9b59b6", "#3498db", "#e74c3c"],
    sizes: [],
    image: "https://images.unsplash.com/photo-1601925228088-b0d0b1a6bf4e?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1601925228088-b0d0b1a6bf4e?w=600&q=80"],
    description: { fr: "Tapis antidérapant éco-responsable en caoutchouc naturel. Idéal pour yoga et pilates.", en: "Eco-friendly non-slip mat in natural rubber. Perfect for yoga and pilates.", de: "Umweltfreundliche rutschfeste Matte aus Naturkautschuk.", es: "Esterilla antideslizante ecológica de caucho natural. Perfecta para yoga y pilates." },
    specs: { fr: "183x61cm · 4mm · Caoutchouc naturel · Sac inclus", en: "183x61cm · 4mm · Natural rubber · Bag included", de: "183x61cm · 4mm · Naturkautschuk · Tasche inklusive", es: "183x61cm · 4mm · Caucho natural · Bolsa incluida" }
  }
];

const orders = [
  { id: "ORD-2024-001", date: "2024-01-15", status: "delivered", total: 439.98, items: [{productId: 1, qty: 1}, {productId: 3, qty: 1}], customer: "Marie Dupont", email: "marie@example.com" },
  { id: "ORD-2024-002", date: "2024-01-20", status: "shipped", total: 189.99, items: [{productId: 2, qty: 1}], customer: "Jean Martin", email: "jean@example.com" },
  { id: "ORD-2024-003", date: "2024-01-22", status: "processing", total: 329.98, items: [{productId: 4, qty: 1}, {productId: 6, qty: 1}], customer: "Sophie Bernard", email: "sophie@example.com" },
  { id: "ORD-2024-004", date: "2024-01-23", status: "pending", total: 129.99, items: [{productId: 5, qty: 1}], customer: "Lucas Petit", email: "lucas@example.com" },
  { id: "ORD-2024-005", date: "2024-01-24", status: "delivered", total: 219.98, items: [{productId: 7, qty: 2}, {productId: 12, qty: 1}], customer: "Emma Leroy", email: "emma@example.com" },
  { id: "ORD-2024-006", date: "2024-01-25", status: "shipped", total: 159.99, items: [{productId: 8, qty: 1}], customer: "Thomas Moreau", email: "thomas@example.com" },
];
